#!/usr/bin/env bash
# Script that transfers a file from our client to a server.
if [$# -lt 3];
then
     Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
else
    file_path=$1
    ip=$2
    user=$3
    ssh_path=$4
    scp -i "$ssh_path" -o StrictHostKeyChecking=no "$file_path" "$user@$ip:~/" 
fi
