#!/usr/bin/env bash
# Script that installs and configures nginx on your web-01 server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
touch /var/www/html/index.html
echo "Holberton School" | tee /var/www/html/index.html
new="server_name bendosch.tech;\n\tlocation \/redirect_me {\n\t\t#redirect task\n\t\t\treturn 301 http:\/\/www.google.com;\n\t}\n"
sed -i 's/server_name _;/$new/' /etc/nginx/sites-available/default
service nginx restart
