#!/usr/bin/env bash
# Script that installs and configures nginx on your web-01 server
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo touch /var/www/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.html
new="server_name bendosch.tech;\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch\\?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "s/server_name _;/$new/" /etc/nginx/sites-enabled/default
sudo service nginx restart
