#!/usr/bin/env bash
# Script that installs and configures nginx on your web-01 server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo touch /var/www/html/index.html
sudo touch /var/www/html/error404.html
echo "Holberton School" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
sudo sed -i 's/server_name _;/server_name bendosch.tech;\n\tlocation \/ {\n\t\t#redirect task\n\t\treturn 301 http:\/\/www.google.com;\n\t}\n\n\terror_page 404 \/error404.html;\n\tlocation = \/error404.html {\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default
sudo service nginx restart
