#!/usr/bin/env bash
#Prints "Holberton School" 10 times, follows teh 9th with "Hi"
LIMIT=10
i=1

while [ $i -le $LIMIT ]
do
    echo "Holberton School"
    if [ $i -eq 9 ]
    then
	echo "Hi"
    fi
    let "i+=1"
done
