#!/usr/bin/env bash
#Prints "Holberton School" 10 times, repaces the 9th with "Hi"
LIMIT=10
i=1

while [ $i -le $LIMIT ]
do
    if [ $i -eq 9 ]
    then
	echo "Hi"
    else
	echo "Holberton School"
    fi
    let "i+=1"
done
