#!/usr/bin/env bash
#Prints "Holberton School" 10 times. Replaces lucky and unlucky numbers.
LIMIT=10
i=1

while [ $i -le $LIMIT ]
do
    if [ $i -eq 4 ]
    then
	echo "bad luck"
    elif [ $i -eq 8 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    let "i+=1"
done
