#!/usr/bin/env bash
LIMIT=20
i=1

while [ $i -le $LIMIT ]
do
    case $i in

	4)
	    echo "bad luck from China"
	    ;;
	8)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
	*)
	    echo $i
	    ;;
    esac
    let "i+=1"
done
