#!/usr/bin/env bash
#prints "Holberton School" 10 times. Notes bad luck numbers from countries
LIMIT=20
i=1

while [ $i -le $LIMIT ]
do
    echo $i
    case $i in

	4)
	    echo "bad luck from China"
	    ;;
	8)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    let "i+=1"
done
